apiVersion: v1
kind: Pod
metadata:
  name: secret-test
spec:
  serviceAccountName: default
  containers:
    - name: app
      image: public.ecr.aws/docker/library/busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets"
          readOnly: true
  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: aws-secrets-test
